一、基础创建与查看

In [1]:
#1.导入 pandas，用字典创建DataFrame
import pandas as pd
data1= {
    'name': ['Tom', 'Jerry', 'Mike'],
    'score': [85, 92, 78],
    'gender': ['男', '女', '男']
}
df1 = pd.DataFrame(data1)
df1

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [2]:
#2.查看上述 DataFrame 的前 1 行、形状、列名、数据类型。
print("\n前1行数据:",df1.head(1))
print("\n数据形状(行数,列数):", df1.shape)
print("\n列名:", df1.columns.tolist())
print("\n数据类型:",df1.dtypes)

前1行数据:   name  score gender
0  Tom     85      男

数据形状(行数,列数): (3, 3)

列名: ['name', 'score', 'gender']

数据类型: name      object
score      int64
gender    object
dtype: object

In [3]:
# 3. 用列表创建DataFrame
data2 = [[1, "A"], [2, "B"], [3, "C"]]
df2 = pd.DataFrame(data2, columns=["id", "tag"])
df2

   id tag
0   1   A
1   2   B
2   3   C

二、列与行操作

In [4]:
# 1. 选取 score 和 gender 两列
df1[['score', 'gender']]

   score gender
0     85      男
1     92      女
2     78      男

In [5]:
# 2. 选取索引 0、2 的行
df1.loc[[0, 2]]

   name  score gender
0   Tom     85      男
2  Mike     78      男

In [6]:
# 3. 筛选 score>80 的行
df1[df1["score"] > 80]

    name  score gender
0    Tom     85      男
1  Jerry     92      女

In [7]:
# 4. 新增grade列：score≥90为优秀，否则为良好
df1["grade"] = df1["score"].apply(lambda x: "优秀" if x >= 90 else "良好")
print("\n4. 新增grade列后：")
print(df1)

4. 新增grade列后：
    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

In [8]:

# 5. 删除gender列
df1_drop = df1.drop(columns="gender")
print("\n5. 删除gender列后：")
print(df1_drop)

5. 删除gender列后：
    name  score grade
0    Tom     85    良好
1  Jerry     92    优秀
2   Mike     78    良好

三、缺失值

In [9]:
# 1. 创建含缺失值的DataFrame，检测缺失值并统计每列缺失数量
data = {"x":[1, None, 3], "y":[None, 5, 6]}
df = pd.DataFrame(data)
print("原始含缺失值的DataFrame:")
print(df)

# 检测缺失值
print("\n缺失值布尔检测:")
print(df.isnull())

# 统计每列缺失数量
print("\n每列缺失值数量:")
print(df.isnull().sum())

原始含缺失值的DataFrame:
     x    y
0  1.0  NaN
1  NaN  5.0
2  3.0  6.0

缺失值布尔检测:
       x      y
0  False   True
1   True  False
2  False  False

每列缺失值数量:
x    1
y    1
dtype: int64

In [10]:
# 2. 用0填充缺失值；删除含缺失值的行
df_fill = df.fillna(0)
print("\n用0填充缺失值后：")
print(df_fill)

df_drop = df.dropna()
print("\n删除含缺失值的行后：")
print(df_drop)

用0填充缺失值后：
     x    y
0  1.0  0.0
1  0.0  5.0
2  3.0  6.0

删除含缺失值的行后：
     x    y
2  3.0  6.0

四、分组聚合

In [11]:
# 1. 按 gender 分组，求 score 的均值和最大值
result1 = df1.groupby('gender')['score'].agg(['mean', 'max'])
print("按 gender 分组的 score 均值和最大值：")
print(result1)

按 gender 分组的 score 均值和最大值：
        mean  max
gender
女       92.0   92
男       81.5   85

In [12]:
# 2. 按 gender 分组，统计每组人数
result2 = df1.groupby('gender').size()
print("\n按 gender 分组的每组人数：")
print(result2)

按 gender 分组的每组人数：
gender
女    1
男    2
dtype: int64

五、排序与去重

In [13]:
# 1. 按 score 升序排序
df_sorted = df1.sort_values(by='score', ascending=True)
print("按 score 升序排序后的 DataFrame：")
print(df_sorted)

按 score 升序排序后的 DataFrame：
    name  score gender grade
2   Mike     78      男    良好
0    Tom     85      男    良好
1  Jerry     92      女    优秀

In [14]:
# 2.添加重复数据（Tom,85,男）
new_row = pd.DataFrame([{"name": "Tom", "score": 85, "gender": "男"}])
df = pd.concat([df1, new_row], ignore_index=True)
print("\n添加重复数据后:")
print(df)

# 去重（默认保留第一次出现的行）
df_dedup = df.drop_duplicates(keep="first")
print("\n去重后:")
print(df_dedup)

添加重复数据后:
    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好
3    Tom     85      男   NaN

去重后:
    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好
3    Tom     85      男   NaN

六、合并与拼接

In [15]:
# 1. 横向合并（按id内连接）
df1 = pd.DataFrame({"id":[1,2], "name":["X","Y"]})
df2 = pd.DataFrame({"id":[1,2], "age":[20,30]})
df_merge = pd.merge(df1, df2, on="id")
print("1. 横向合并结果：")
print(df_merge)

1. 横向合并结果：
   id name  age
0   1    X   20
1   2    Y   30

In [16]:
# 2. 纵向拼接并重置索引
df_a = pd.DataFrame({"val":[1,2]})
df_b = pd.DataFrame({"val":[3,4]})
df_concat = pd.concat([df_a, df_b], ignore_index=True)
print("\n2. 纵向拼接并重置索引结果：")
print(df_concat)

2. 纵向拼接并重置索引结果：
   val
0    1
1    2
2    3
3    4

七、时间处理

In [17]:
# 1. 创建时间列，转为datetime格式
date_list = ["2025-01-01","2025-01-02","2025-01-03"]
df = pd.DataFrame({"date": date_list})
df["date"] = pd.to_datetime(df["date"])
print("1. 转换为datetime格式：")
print(df)

1. 转换为datetime格式：
        date
0 2025-01-01
1 2025-01-02
2 2025-01-03

In [18]:
# 2. 提取月份、星期
df["month"] = df["date"].dt.month
df["weekday"] = df["date"].dt.day_name()   # 英文星期
# df["weekday_cn"] = df["date"].dt.dayofweek+1  # 数字星期(1=周一,7=周日)
print("\n2. 提取月份、星期：")
print(df)

2. 提取月份、星期：
        date  month    weekday
0 2025-01-01      1  Wednesday
1 2025-01-02      1   Thursday
2 2025-01-03      1     Friday

八、高级操作

In [19]:
data1 = {
    'name': ['Tom', 'Jerry', 'Mike'],
    'score': [85, 92, 78], 
    'gender': ['男', '女', '男']
}
df1 = pd.DataFrame(data1)

# 1. 对 score 列做标准化
score_mean = df1['score'].mean()
score_std = df1['score'].std(ddof=0)
df1['score_standardized'] = (df1['score'] - score_mean) / score_std

print("\n标准化后的数据:")
print(df1)

标准化后的数据:
    name  score gender  score_standardized
0    Tom     85      男            0.000000
1  Jerry     92      女            1.224745
2   Mike     78      男           -1.224745

In [20]:
# 2. 透视表：按 gender 分组，计算 score 中位数
pivot_result = df1.pivot_table(
    index='gender',
    values='score',
    aggfunc='median'
)

print("\n按 gender 分组的 score 中位数：")
print(pivot_result)

按 gender 分组的 score 中位数：
        score
gender
女        92.0
男        81.5